[project]
name = "tokenized_market"
authors = []
description = ""
telemetry = true
requirements = []
[contracts.tokenized_prediction]
path = "contracts/tokenized_prediction.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
